travis:
  secure:
    BINSTAR_TOKEN: dwfuUxOmokrhlfgce+o1U1E3scGBpzy0Vu6M5M+pczCV9bfXP59H3B+kYjB5O6NPE6M41z4vuSNvB3GFumr/MqWtR2I6vyUVf9emy0FwyS4mceXkHC8cgFSt75xwgFgHOKqNIW660uA65IxL5GcRETK4J/5GpSMGI2vCC6C6GSyjS1zTE1QGRG3edoIUBjIbwtdNW1cfjK5C8+TxBPTRqv++MPM1Tr0xlo7a18Pra3W5UPftgCgypkdTMalYSMSmsHQgDaVy21jz2Mbnex7HC6Y8a806NoBywQRhK1211acFfQlVYpyaVId8VXz59R0OlA5TEB6C0jrUdlH21mtG+gEoX881XVfybIwpLXjNxp4Pdrd60oZ6fuy1ucv0hD3XtqVFjDDbZDEvj4VFR5fJkQrKc+u7vMLuaTejhg8YEBe+Zj7S/cXGI41lNDTWSrpcphoF6aKE6kvlsl4meF/85YO5aG5S7G2IwvDMaiUpfkQ5/CjYDqrvUSABlZ8p0PZbD2PF/ZJTWyV5VRxYprKMELheokeas06C5FhVk04IXwEOHo0fpWAyWJWYUb8wlCOarQkObp53eKJHAG/G75jY31wWyRCQalo/pcnLfzQfQZXwf132Pts6GaCFqpqIp82z7WhwVkTnBLusqJn5MFxnXxyZjN7gvE37ophuB8d8SGo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
