travis:
  secure:
    BINSTAR_TOKEN: jjQwZdk+24t+1R9LDB7OtJyiZaOzPDbT31D1J4LaNBOSl2jxYDADLy/zwDMxqidal7Tyxyn+jKhMtJaAaE94MR5r2/h8oS6LyvGcUtauILFR2oL33uTKnhFvKGkfPoS01OvATKMYTI1OpFylORRs0RKGtfJJMkwrZI6FdZkVxbaamf1ubizcqWqFME/IlcW8KH3K3xgRBeXAvaaV1fK/AlkeEHCU50BivdO+jJB7YwLVRwmPUWOGN08+qHd136woWFXlRoE6nNL5SNC2ZE2ZQH5jxrOm6k8QjkTkAQQ+RM/CSDy9T5jqS4DikOQ4mqAoPJQbSNszDi4/A8TAFMf2+jQnomDGsUQDEOqLoF0FEVBC48O8YAmrxA58pJzpPQaGJrPjjqfGUUL3dJCcDF/eofalldMhqjH4gfD9jImP5NKr7MF8az1cdxmUeMj6tyXN/nABAu6JeTWpRXDGl49mh4/mUJY8HZzcVMKwIOamLrC3DGaXplpCBh8tiCD2yXYOiotZKHESmJznO2PAr4X5el9ePcbJ97Kx5C6OqcHbEbeLuWKOIuUQuIlMJIwu1NPA6xn5j0EEam5Irw69l5WyT9Zf2o8u83GglIs5umkMFZaMDjtsLWshY2v+DHeakHJALMxjUNenPAL5tsHvWwjLesKnvIkgAWHraKN/C2rJ6ho=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
