travis:
  secure:
    BINSTAR_TOKEN: bAN9SY1cKxfEnap8SQaneuT3x3v71sgYFRxWnbhi/guqf8Xpqmg7pUmZfhkDVGu6j7RXuHUOBENJ3NVOxjC85xuXsomtTthbK0PEmzviBp++NjuLodU3aSqGQiLdXfNpvzm2F7e5iqj41Vs8vlMZ/FaG9wqYRFiUreSxZ9QXTsCyfqdeI6XzN3K8jWyTtN/kiqmI+Ad080LTLSRsevMxVcODsDbjHy8XZrrzc4b9s3Q5rSAVPs+Yx9NFRtonwKJFX4kvVdow3Rf2fpV9bwwS3QGDC8ucc7FYMEeKP3+thDN1pWnN7G/W2zMtyCX2ZC1noULmYc5sIeXX6De7CI9zcwA8S5CuIWWJrkrVgkutdmeDqrRFYwe/e99W0Ba76GpbaLxD6caWn9BSvPh+qy1/LNfou229M5w6dp4zTvGgJhWmmoX3Q8E7Py1gc4cB72GqEN3H0DH82XLGUtW3F+daL/pgwE8iNFvv2kUlGLV1RE0OqMGlRmrJ2xAsmK+VTB9ks+SZ84qU8NMdUxumkp5ECbT5lYBa9ZCDDHQywr3HDTgBcyQrokEHMpqncg2xPqXK9KcWSSl83O4aeqphroeYt739sCF+6PNg4HbIUfAqxFvfieZg36MD4Db/malDZZ6xCw2Vwabnuwcdz3pqDWmF3yrECOJ2f8hfW/u0OaBpJ/Q=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
