travis:
  secure:
    BINSTAR_TOKEN: DAJezhGGbyPAAzmBFoDdUs2UDzkH10dKeGvhKndZ/kQH0GZk0Wh8DKNS2plGggW+DZ/e8MiJnvuj8jtYWkFw81dUGrhSE4cFtOtRVHU4KQ+p8S93LssiyrP9d9pbFQCzCe8txlfB1fd7E0835tXHEe1SOxt3k5QGwJ58ULe2RT7qdMdUAwxN1SSrur5c1FZeb3nHMbFtExmzr1j6bPZrvzvTOQBA84oke6BBFtX8IyURT6DCynByHISXLEdkO/vkh4SvLCqcS4hzGovLaPWYmIsgtE9oSALwYrr4jnlntXlf5wYkLlQ0Sr1wA+KNwWKyKWz+cSszUOS9AHs0u52v3qSJKSHAmRuuztRey5cMGtQ0bXzynHTEc+Ie8M7UhNRnN84nOso0FLNTok5zLNtcYcLpkuQWNZcGP9pyKxF7iQ4ZpeMYirDmuhi6T6RYYKJww6k/9TtRda+eEsjRnsm4VHb6JYj/yosABo3StgQ9SmD1lXOGXoFiNoVDwAqXH/1u5BTA28zhlRN+adZVN9XaCCI8PngMeqNm14UZhnsZX0NN2RU6Pef4iAAYBO+r3p9eD2rFRkoglXZp0rdF6yL2xqKDCGpNZCI9ivZd2IsHf+6WmJMLOsgCFQJ0TEFm5uqR73KRsHUM30SUIJMLLPiRdOh+G6na+mcEePWViMHX6k4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
