travis:
  secure:
    BINSTAR_TOKEN: f1sC9yPFmBUIqLZDkK5XjSM4I+Cd+EIGbHwJVS06WUDt/pe+EfmpWMEgDa0cbZh8TcMpPOq7w2oaVoQxwIKrhySC9nTOk7FOLqsyLQIsFYbg3snM6DRIu+vYkXRSBoQGOSEl3g61Jd13DCdpcmv5FVkzsD/++k5izPdsp+afC+90lRttu52ZXJeMO6rFjQZjJfAr8t9WZXKgUO+YC0pVM/5LMqgDubMblpoEmnqhvkuHtDl77mv4Pz3AUnASJ2eTsky0Aksg83BrLRme+Jr98uWZah8uVZN+VR0GZoI3cfeRQHu7UnDOjz3VijcB9MFmUpKSiCWYruztx3lTO4vNxJymlNI57F4L63iSsyfQBNHQAPNJS/iOoyDXQjWSL5J8lKgp5W2B422BfifAQkkPeOpcohBC+oJwr40n0nNyRJsFBcFzPxz3dJf7DJM5VPrWSwblOuVth/voT4RF3PG4CkuhVGZGG3xJ8wReUXDeWbAH8i99ta6wxBXKsyjA9+wraQXe/aSwSjnn5/5Pp9me5nBZWuI4kOyDDsQR3a81zjzKEvkA8+NSP2dk7UDSc8asNyr4B/W8IV0Bg+iLbCH9NSZWVGq/Z0GFopZ8Tnn6xdw4C5EYSfhb3OHXqSizzI2owu4sslJ00szZ25nYumUc/6G81Xb2zQmfGgsLyDOCRu8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
